title: Researcher
url: "https://gabrielyeo.com"
baseurl: "/researcher"

markdown: kramdown
ins_logo: "./NUS_logo.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/gb3h"
footer_text: "Page design from Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
